[package]
name = "zeta_fn"
version = "0.1.0"
authors = ["Zeno343"]
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2.3"

[dependencies.teensy4-bsp]
version = "0.3"
features = ["rt"]

[profile.release.build-override]
opt-level = 0
